config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :users
  
  get '/signin' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :activities do
    resources :item_categories, name_prefix: "activity_"
  end
  
  resources :item_categories do
    resources :item_models, name_prefix: "item_category_"
  end

  resources :item_models

  resources :item_model_characteristics, only: [:new, :create, :show] do
    resources :ratings, name_prefix: "item_model_characteristic_"
  end

  resources :characteristics
  
  resources :ratings

  
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get 'google_login', to: redirect("/auth/google_oauth2")
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
    has_many :item_models
    has_many :characteristics, through: :item_models
    belongs_to :activity

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
    before_action :require_log_in

    def new
        if !@item_category
            @item_category = ItemCategory.new
        end

        if params[:activity_id]
            @activity = Activity.find_by(id: params[:activity_id])
        else
            
        end
    end

    def create
        
        @item_category = ItemCategory.new(item_category_params)
        
        @activity = Activity.find_by(id: params[:parent][:parent_id])
        @item_category.activity = @activity

        if @item_category.save
            redirect_to activity_item_category_path(@activity, @item_category)
        else
            render :new
        end
    end

    def show
        @item_category = ItemCategory.find_by(id: params[:id])
        
    end

    def index

    end

    private

    def item_category_params
        params.require(:item_category).permit(:name, :description)
    end

end

app/views/item_categories/index.html.erb
<h2>All Item Categories by Activity</h2>

<%Activity.all.each do |activity|%>
    <h4><%=link_to activity.name, activity_path(activity)%></h4>

    <div>
    <ul style="list-style-type:none">
    <%activity.item_categories.each do |item_cat|%>
        <li><%=link_to item_cat.name, item_category_path(item_cat)%></li>
    <%end%>
    </ul>
    </div>

<%end%>

app/views/item_categories/new.html.erb
<h2>Create a new Item Category</h2>

<%=render partial: 'activities/form', locals: {current_object: @item_category, parent_object: @activity ||=Activity.new}%>

app/views/item_categories/show.html.erb
<h2><%=@item_category.name%></h2>

<p class="desc"><%=@item_category.description%></p>

<h3>Belongs to: <%=link_to @item_category.activity.name, activity_path(@item_category.activity)%></h3>

<h3>Specific Models:</h3>

<h4><%=link_to "Add a new Model", new_item_category_item_model_path(@item_category)%></h4>

<ul>
    <%ItemModel.sorted_by_overall_rating_desc(@item_category).each do |item_model|%>
        <li><%=link_to "#{item_model.name} - Rating: #{item_model.overall_rating}", item_category_item_model_path(item_model)%></li>
    <%end%>
</ul>