config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :users
  
  get '/signin' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :activities do
    resources :item_categories, name_prefix: "activity_"
  end
  
  resources :item_categories do
    resources :item_models, name_prefix: "item_category_"
  end

  resources :item_models

  resources :item_model_characteristics, only: [:new, :create, :show] do
    resources :ratings, name_prefix: "item_model_characteristic_"
  end

  resources :characteristics
  
  resources :ratings

  
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get 'google_login', to: redirect("/auth/google_oauth2")
end

app/models/item_model.rb
class ItemModel < ActiveRecord::Base
    has_many :item_model_characteristics
    has_many :characteristics, through: :item_model_characteristics
    belongs_to :item_category

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    def overall_rating
        
        if !self.item_model_characteristics.empty?
            total_rating = []
            self.item_model_characteristics.each do |imc|
                if numeric?(imc.average_rating)
                    imc.review_count.times do
                        total_rating.push(imc.average_rating)
                    end
                end
            end
            
            if total_rating.empty?
                total_rating = "No Ratings for any characteristics"
            else
                (total_rating.inject(0.0){|sum, num| sum + num}/total_rating.size).round(2)
            end
            
        else
            total_rating = "No Ratings for any characteristics"
        end
    end

    def self.by_item_category(item_category)
        ItemModel.where(["item_category_id = ?", item_category.id])
    end

    def self.sorted_by_overall_rating_desc(item_category)
        self.by_item_category(item_category).sort_by(&:overall_rating).reverse
    end

    private

    def numeric? string
        true if Float(string) rescue false
    end
end

app/controllers/item_models_controller.rb
class ItemModelsController < ApplicationController
    before_action :require_log_in

    def show
        @item_model = ItemModel.find_by(id: params[:id])
        if !@item_model_characteristic
            @item_model_characteristic = ItemModelCharacteristic.new
        end
        
        if !@characteristic
            @characteristic = Characteristic.new
        end
    end

    def new
        if !@item_model
            @item_model = ItemModel.new
        end

        if params[:item_category_id]
            @item_category = ItemCategory.find_by(id: params[:item_category_id])
        else
            
        end
    end

    def create
        @item_model = ItemModel.new(item_model_params)
        @item_category = ItemCategory.find_by(id: params[:parent][:parent_id])
        @item_model.item_category = @item_category

        if @item_model.save
            redirect_to item_category_item_model_path(@item_category, @item_model)
        else
            render :new
        end
    end

    private

    def item_model_params
        params.require(:item_model).permit(:name, :description)
    end
end

app/views/item_models/_add_char_form.html.erb
<div>
    <h4>Add a Characteristic to <%=model.name%></h4>


    <%=form_for imc do |f|%>
        <% if imc.errors.any? %>
        <div id="error_explanation">
          <h2>There were some errors:</h2>
          <ul>
            <% imc.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%=hidden_field_tag 'item_model[id]', model.id%>

        <%=f.label "Select a Characteristic"%>
        <%=f.collection_select(:characteristic_id, Characteristic.all, :id, :name, prompt: true)%><br><br>

        <%=f.label "OR create a new Characteristic"%><br><br>
        <%=fields_for :characteristic do |fields|%>
            <%=fields.label "New Characteristic Name"%><br>
            <%=fields.text_field :name%><br><br>

            <%=fields.label "New Characteristic Description"%><br>
            <%=fields.text_area :description%><br><br>
        <%end%>

        <%=f.submit "Add Characteristic to #{model.name}", class: "btn btn-outline-dark"%>
    <%end%>
</div>

app/views/item_models/_char_display.html.erb
<%if !Characteristic.all.empty?%>
    <%item_model_characteristics.each do |item_model_char|%>
        <%characteristic = item_model_char.characteristic%>
        <%=link_to characteristic.name, characteristic_path(characteristic)%><br>
        Total Number of Reviews: <%=item_model_char.review_count%> <br> 
        Average Review: <%=item_model_char.average_rating%><br>
        <%=link_to "All reviews for this product's #{characteristic.name}", item_model_characteristic_path(item_model_char)%><br>
        <%if !item_model_char.ratings.where(user_id: current_user.id).empty?%>
            <%rating = Rating.from_parent(user: current_user, item_model_characteristic: item_model_char)%>
            Your current rating: <%=link_to rating.rating, rating_path(rating)%> - <%=link_to "Edit Rating", edit_rating_path(rating)%> <br>
        <%else%>
            <%=link_to "Click to add Review", new_item_model_characteristic_rating_path(item_model_char)%><br>
        <%end%>
        <br>
    <%end%>
<%end%>

app/views/item_models/new.html.erb
<h2>Add a new Model</h2>

<%=render partial: 'activities/form', locals: {current_object: @item_model, parent_object: @item_category||=ItemCategory.new}%>

app/views/item_models/show.html.erb
<h2><%=@item_model.name%> Details</h2>

<p class="desc"><%=@item_model.description%></p>

<h3>Product Item Category/Activity:</h3>

<h4>Activity: 
<%=link_to @item_model.item_category.activity.name, activity_path(@item_model.item_category.activity)%>
</h4>

<h4>Item Category:
<%=link_to @item_model.item_category.name, item_category_path(@item_model.item_category)%><br>
</h4>


<h3>Product Characteristics:</h3>
<h4>Product Overall Rating: <%=@item_model.overall_rating%></h4>

<br>

<%if params[:add_char]%>
    <%=render partial: 'add_char_form', locals: {model: @item_model, char: @characteristic, imc: @item_model_characteristic}%>
<%else%>
    <%=link_to "Sort by Avg Review", item_model_path(@item_model, sort: "review")%><br>
    <%=link_to "Sort by Review Count", item_model_path(@item_model, sort: "count")%><br><br>
    <%=render partial: 'char_display', locals: {item_model_characteristics: ItemModelCharacteristic.sort_by_param({item_model: @item_model, sort_type: params[:sort]})}%>
    <h4><%=link_to "Add a Characteristic", item_model_path(@item_model, add_char: true)%></h4>
<%end%>