config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :users
  
  get '/signin' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :activities do
    resources :item_categories, name_prefix: "activity_"
  end
  
  resources :item_categories do
    resources :item_models, name_prefix: "item_category_"
  end

  resources :item_models

  resources :item_model_characteristics, only: [:new, :create, :show] do
    resources :ratings, name_prefix: "item_model_characteristic_"
  end

  resources :characteristics
  
  resources :ratings

  
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get 'google_login', to: redirect("/auth/google_oauth2")
end

app/models/user.rb
class User <ActiveRecord::Base

    has_secure_password
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    has_many :ratings

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :load_user, only: [:show, :edit]
    before_action :require_log_in, only: [:show, :index]

    def new
        if !@user
            @user = User.new
        end
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show

    end

    def index

    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

    def load_user
        User.find_by(id: params[:id])
    end
end

app/views/users/index.html.erb
Lists all the users!

app/views/users/new.html.erb
<%=form_for @user do |f|%>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>There were some errors:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    
    <%=f.label :name, "Username"%><br>
    <%=f.text_field :name%><br><br>

    <%=f.label :email, "E-mail Address:"%><br>
    <%=f.text_field :email%><br><br>
    
    <%=f.label :password%><br>
    <%=f.password_field :password%><br><br>

    <%=f.submit "Sign Up!", class: "btn btn-outline-dark"%>

    Or <%=link_to "Login with Google", google_login_path%><br>

<%end%>

app/views/users/show.html.erb
<h2><%=current_user.name%> Page</h2>

<h3><%=link_to "Explore Activities", activities_path%></h3>

<h3>Ratings:</h3>

<ul>
    <%current_user.ratings.each do |rating|%>
        <li><%=link_to "#{rating.item_model.name}", item_model_path(rating.item_model)%>
        - <%=link_to "#{rating.characteristic.name}", characteristic_path(rating.characteristic)%> - 
        <%=link_to "#{rating.rating}", rating_path(rating)%></li>
    <%end%>
</ul>