config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :users
  
  get '/signin' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :activities do
    resources :item_categories, name_prefix: "activity_"
  end
  
  resources :item_categories do
    resources :item_models, name_prefix: "item_category_"
  end

  resources :item_models

  resources :item_model_characteristics, only: [:new, :create, :show] do
    resources :ratings, name_prefix: "item_model_characteristic_"
  end

  resources :characteristics
  
  resources :ratings

  
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get 'google_login', to: redirect("/auth/google_oauth2")
end

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
      <ul class="nav navbar-nav">
        <%if current_user%>
            <li class="dropdown pc-menu">
                <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <span id="user-name"><%= current_user.name %></span>
                    <span class="caret"></span>
                </a>

                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li><%= link_to 'Activities', activities_path %></li>
                  <li><%= link_to 'Log out', signout_path,  method: :delete %></li>
                </ul>
            </li>
        <%else%>
            <li><%=link_to "Sign In", signin_path%></li>
            <li><%=link_to "Sign Up", new_user_path%></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
      <%=link_to "Specialty Review", root_path, class: 'navbar-brand'%>
</div>